Evaluation:
    type: entity
    table: evaluation
    indexes:
        FK_Association3:
            columns:
                - IdUser
        FK_Association4:
            columns:
                - IdDeal
    id:
        idevaluation:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: IdEvaluation
            generator:
                strategy: IDENTITY
    fields:
        commentaire:
            type: string
            nullable: true
            length: 254
            fixed: false
            comment: ''
            column: Commentaire
        note:
            type: string
            nullable: true
            length: 254
            fixed: false
            comment: ''
            column: Note
    manyToOne:
        iddeal:
            targetEntity: Deal
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                IdDeal:
                    referencedColumnName: IdDeal
            orphanRemoval: false
        iduser:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                IdUser:
                    referencedColumnName: IdUser
            orphanRemoval: false
    lifecycleCallbacks: {  }
