admin_admin_homepage:
    pattern:  /Admin/index
    defaults: { _controller: AdminAdminBundle:Default:index }
    
    
    
    
    
admin_admin_morris:
    pattern:  /Admin/morris
    defaults: { _controller: AdminAdminBundle:Default:morris }



admin_admin_client:
    pattern:  /Admin/client
    defaults: { _controller: AdminAdminBundle:Default:client }