admin_admin_homepage:
    pattern:  /Admin/index
    defaults: { _controller: AdminAdminBundle:Default:index }
    
    
    
    
    
admin_admin_morris:
    pattern:  /Admin/morris
    defaults: { _controller: AdminAdminBundle:Default:morris }

admin_admin_client:
    pattern:  /Admin/client
    defaults: { _controller: AdminAdminBundle:Default:client }
    
admin_admin_prest:
    pattern:  /Admin/prestataire
    defaults: { _controller: AdminAdminBundle:Default:prestataire }

admin_admin_deal:
    pattern:  /Admin/deal
    defaults: { _controller: AdminAdminBundle:Default:deal }
    
admin_admin_deal_a_Valider:
    pattern:  /Admin/deal_a_Valider
    defaults: { _controller: AdminAdminBundle:Default:deal_a_Valider }

admin_admin_ValiderD:
    pattern:  /Admin/ValiderD/{id}
    defaults: { _controller: AdminAdminBundle:Default:ValiderD }
    

client_supprimer:
    pattern:  /Admin/supprimerC/{id}
    defaults: { _controller: AdminAdminBundle:Default:supprimerC }
    
prest_supprimer:
    pattern:  /Admin/supprimerP/{id}
    defaults: { _controller: AdminAdminBundle:Default:supprimerP }
    
deal_supprimer:
    pattern:  /Admin/supprimerD/{id}
    defaults: { _controller: AdminAdminBundle:Default:supprimerD }    