Reservation:
    type: entity
    table: reservation
    indexes:
        FK_Association1:
            columns:
                - IdUser
        FK_Association2:
            columns:
                - IdDeal
    id:
        idreservation:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: IdReservation
            generator:
                strategy: IDENTITY
    fields:
        datereservation:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
            column: DateReservation
        quantite:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: Quantite
    manyToOne:
        iddeal:
            targetEntity: Deal
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                IdDeal:
                    referencedColumnName: IdDeal
            orphanRemoval: false
        iduser:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                IdUser:
                    referencedColumnName: IdUser
            orphanRemoval: false
    lifecycleCallbacks: {  }
