Statistique:
    type: entity
    table: statistique
    indexes:
        FK_Association6:
            columns:
                - IdUser
    id:
        idstatistique:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: IdStatistique
            generator:
                strategy: IDENTITY
    fields:
        datedebut:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
            column: DateDebut
        datefin:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
            column: DateFin
        categorie:
            type: string
            nullable: true
            length: 254
            fixed: false
            comment: ''
            column: Categorie
    manyToOne:
        iduser:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                IdUser:
                    referencedColumnName: IdUser
            orphanRemoval: false
    lifecycleCallbacks: {  }
